//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCar.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCar()
        {
            this.tblRezervations = new HashSet<tblRezervation>();
        }
    
        public int CarId { get; set; }
        public int ModelId { get; set; }
        public int RegistrationNumber { get; set; }
        public int LocationId { get; set; }
        public bool isRent { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblModel tblModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRezervation> tblRezervations { get; set; }
    }
}
